### ISSUE TITLE
foolbar版新彩e打算接纳吗

### ISSUE THREAD

**Issue by JustSoYouKnow** [liufuyou/EhViewer#12]
如题

**Comment by liufuyou** [comment]
谢谢issues，会的

在今天凌晨1点浏览到您的问题时，由于疲劳，打算睡觉后再做回答，一觉醒来遗忘了，抱歉。现在回复您，对此表示诚挚的歉意。如果有任何进一步的问题或需要讨论的事宜，敬请告知
